codecov:
  notify:
    require_ci_to_pass: yes
  strict_yaml_branch: master  # only use the latest copy on master branch

coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        enabled: yes
        target: 90%
    patch:
      default:
        enabled: yes
        target: 95%

ignore:
  - **/*/metadata/generated_metrics.go
