language: go
cache:
  directories:
    - /home/travis/gopath/pkg/mod

go_import_path: github.com/open-telemetry/opentelemetry-collector

go:
  - 1.13.x

env:
  global:
    - GO111MODULE=on

install:
  - go mod download
  - make install-tools

script:
  - make ci

after_success:
  - bash <(curl -s https://codecov.io/bash)
