l1: cloud
l2: logging
service_name: transaction-tracing
asset_id: 2093065519126984373

code_repo: github.intuit.com/cloud-logging/transaction-tracing.git
deploy_repo: github.intuit.com/cloud-logging/transaction-tracing-deployment.git

argocd_server: "prod-cto.argocd.paas-cplane-prod-west2.a.intuit.com:443"
argocd_password: argocd-transaction-tracing
argocd_project: cloud-logging-transaction-tracing
argocd_project_enabled: true

registry: docker.artifactory.a.intuit.com
repo: cloud/logging/transaction-tracing/service

# change this to false once ready for PRD
preprodOnly: true 
snow_application_name: "TODO"

environments:
  qal:
    cluster: "https://api-pi-ppd-usw2-cluster-k-34umb6-523149175.us-west-2.elb.amazonaws.com"
    namespace: "cloud-logging-transaction-tracing-usw2-ppd-qal"
    region: "usw2"
    iks_type: ppd
    manifest_format: Kustomize

  e2e:
    cluster: "https://api-pi-ppd-usw2-cluster-k-34umb6-523149175.us-west-2.elb.amazonaws.com"
    namespace: "cloud-logging-transaction-tracing-usw2-ppd-e2e"
    region: "usw2"
    iks_type: ppd
    manifest_format: Kustomize

  stg:
    cluster: "https://api-pi-prod-usw2-cluster--6pjuud-2098097015.us-west-2.elb.amazonaws.com"
    namespace: "cloud-logging-transaction-tracing-usw2-prd-stg"
    region: "usw2"
    iks_type: prd
    manifest_format: Kustomize

  prd:
    cluster: "https://api-pi-prod-usw2-cluster--6pjuud-2098097015.us-west-2.elb.amazonaws.com"
    namespace: "cloud-logging-transaction-tracing-usw2-prd-prd"
    region: "usw2"
    iks_type: prd
    manifest_format: Kustomize
